name: Deploy Production to EC2

on:
  push:
    branches:
      - production-aws

jobs:
  deploy:
    name: Deploy Production to EC2
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Start Deployment
        run: echo "Starting deployment process to EC2 instance..."

      - name: 🔑 Connect & Update Code on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ Connected to EC2 instance"
            
            echo "📁 Changing to project directory..."
            cd /home/ec2-user/production/eduall/src || exit

            echo "📦 Fetching latest changes from GitHub"
            git fetch origin
            sudo chown -R ec2-user:ec2-user /home/ec2-user/production/eduall/src/

            echo "🌿 Checking out branch 'production-aws'..."
            git checkout production-aws

            echo "🔄 Resetting local code to match origin/production-aws..."
            git reset --hard origin/production-aws

            echo "✅ Code updated successfully!"

            echo "🔄 Running clear cache and optimization"
            docker exec -i php_eduall bash -c "
              echo '🧹 Fixing permissions...'
              chmod -R 775 storage bootstrap/cache
              chown -R www-data:www-data storage bootstrap/cache
              
              echo '📦 Running composer install inside container...'
              composer install
              
              echo '🧹 Clearing caches...'
              php artisan cache:clear
              php artisan route:clear
              php artisan optimize:clear
            
              echo '✅ Optimization complete!'
            "

      - name: 🎉 Deployment Complete
        run: echo "Deployment finished successfully 🎯"
